/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FolioRouteImport } from './routes/_folio'
import { Route as FolioIndexRouteImport } from './routes/_folio/index'
import { Route as FolioArchiveRouteImport } from './routes/_folio/archive'
import { Route as FolioMetricsRouteImport } from './routes/_folio/metrics'
import { Route as FolioDDateRouteImport } from './routes/_folio/d.$date'

const FolioRoute = FolioRouteImport.update({
  id: '/_folio',
  getParentRoute: () => rootRouteImport,
} as any)
const FolioIndexRoute = FolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FolioRoute,
} as any)
const FolioArchiveRoute = FolioArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => FolioRoute,
} as any)
const FolioMetricsRoute = FolioMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => FolioRoute,
} as any)
const FolioDDateRoute = FolioDDateRouteImport.update({
  id: '/d/$date',
  path: '/d/$date',
  getParentRoute: () => FolioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof FolioIndexRoute
  '/archive': typeof FolioArchiveRoute
  '/metrics': typeof FolioMetricsRoute
  '/d/$date': typeof FolioDDateRoute
}
export interface FileRoutesByTo {
  '/archive': typeof FolioArchiveRoute
  '/metrics': typeof FolioMetricsRoute
  '/': typeof FolioIndexRoute
  '/d/$date': typeof FolioDDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_folio': typeof FolioRouteWithChildren
  '/_folio/archive': typeof FolioArchiveRoute
  '/_folio/metrics': typeof FolioMetricsRoute
  '/_folio/': typeof FolioIndexRoute
  '/_folio/d/$date': typeof FolioDDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/archive' | '/metrics' | '/d/$date'
  fileRoutesByTo: FileRoutesByTo
  to: '/archive' | '/metrics' | '/' | '/d/$date'
  id:
    | '__root__'
    | '/_folio'
    | '/_folio/archive'
    | '/_folio/metrics'
    | '/_folio/'
    | '/_folio/d/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FolioRoute: typeof FolioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_folio': {
      id: '/_folio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_folio/': {
      id: '/_folio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FolioIndexRouteImport
      parentRoute: typeof FolioRoute
    }
    '/_folio/archive': {
      id: '/_folio/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof FolioArchiveRouteImport
      parentRoute: typeof FolioRoute
    }
    '/_folio/metrics': {
      id: '/_folio/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof FolioMetricsRouteImport
      parentRoute: typeof FolioRoute
    }
    '/_folio/d/$date': {
      id: '/_folio/d/$date'
      path: '/d/$date'
      fullPath: '/d/$date'
      preLoaderRoute: typeof FolioDDateRouteImport
      parentRoute: typeof FolioRoute
    }
  }
}

interface FolioRouteChildren {
  FolioArchiveRoute: typeof FolioArchiveRoute
  FolioMetricsRoute: typeof FolioMetricsRoute
  FolioIndexRoute: typeof FolioIndexRoute
  FolioDDateRoute: typeof FolioDDateRoute
}

const FolioRouteChildren: FolioRouteChildren = {
  FolioArchiveRoute: FolioArchiveRoute,
  FolioMetricsRoute: FolioMetricsRoute,
  FolioIndexRoute: FolioIndexRoute,
  FolioDDateRoute: FolioDDateRoute,
}

const FolioRouteWithChildren = FolioRoute._addFileChildren(FolioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  FolioRoute: FolioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
