plugins {
    id 'com.android.application'
}

android {
    namespace 'com.orbit.schedule'
    compileSdk 34

    defaultConfig {
        applicationId "com.orbit.schedule"
        minSdk 26
        targetSdk 34
        versionCode 2
        versionName "1.1"
    }

    signingConfigs {
        release {
            storeFile file("../orbit-release.keystore")
            storePassword "Orbit@2026sched"
            keyAlias "orbit"
            keyPassword "Orbit@2026sched"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
        }
    }
}
