org.gradle.java.home=/root/.local/share/mise/installs/java/17.0.2
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:-UseContainerSupport
android.useAndroidX=true
android.nonTransitiveRClass=true
sdk.dir=/opt/android-sdk
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
systemProp.http.nonProxyHosts=localhost|127.0.0.1
